version: "3.7"
services:
  lamden_events:
    container_name: lamden_events
    image: lamden
    build:
      context: ./lamden/
      args:
        LAMDEN_TAG: ${LAMDEN_TAG?}
        CONTRACTING_TAG: ${CONTRACTING_TAG?}
    working_dir: /lamden/lamden/nodes
    command: sh -c "python events.py -p ${LAMDEN_ES_PORT}"
    volumes:
      - ${HOME}/.lamden:/root/.lamden
    ports:
      - ${LAMDEN_ES_PORT}:${LAMDEN_ES_PORT}
    networks:
      - lamden_network

  lamden_webserver:
    container_name: lamden_webserver
    image: lamden
    depends_on:
      - lamden_events
    working_dir: /lamden/lamden/nodes/masternode
    command: sh -c "python webserver.py -p ${LAMDEN_WS_PORT} -ep ${LAMDEN_ES_PORT}"
    volumes:
      - ${HOME}/.lamden:/root/.lamden
    environment:
      - LAMDEN_SK=${LAMDEN_SK?}
    ports:
      - ${LAMDEN_WS_PORT}:${LAMDEN_WS_PORT}
    networks:
      - lamden_network

  lamden_node:
    container_name: lamden_node
    image: lamden
    depends_on:
      - lamden_webserver
    working_dir: /lamden
    command: sh -c "[ -z ${LAMDEN_BOOTNODES} ] && lamden start -d True || lamden join -d True"
    volumes:
      - ${HOME}/constitution.json:/root/constitution.json
      - ${HOME}/genesis_block.json:/root/genesis_block.json
      - ${HOME}/.lamden:/root/.lamden
    environment:
      - LAMDEN_SK=${LAMDEN_SK?}
      - LAMDEN_TAG=${LAMDEN_TAG?}
      - CONTRACTING_TAG=${CONTRACTING_TAG?}
      - LAMDEN_BOOTNODES=${LAMDEN_BOOTNODES}
    ports:
      - 19000:19000
      - 19080:19080
    networks:
      - lamden_network

networks:
  lamden_network:
    name: lamden_network
